config/routes.rb
Rails.application.routes.draw do

  if MULTILINGUAL

    scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

      # Session resources
      get    'sessions/new'                                 # sessions_new_path
      post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
      delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

      namespace :admin do
        root 'panel#index'                                  # admin_root_path
        resources :users
        resources :growers
        resources :plants
        resources :pictures
        resources :overviews
        resources :articles
        # 1: Add new admin resources before this line
      end

      root   'pages#home'                                   # root_path
      
      get 'pages/deciduous'
      get 'pages/evergreen'
      get 'pages/herbacious'
      get 'pages/pictures'
    end

    # Root route is directed to default locale
    root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

    # All other routes without locales are directed to the same ones with locales
    get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  else

    # Session resources
    get    'sessions/new'                                 # sessions_new_path
    post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
    delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

    namespace :admin do
      root 'panel#index'                                  # admin_root_path
      resources :users
      resources :growers
      resources :plants
      resources :pictures
      resources :overviews
      resources :articles
      # 2: Add new admin resources before this line
    end

    root   'pages#home'                                   # root_path

    get 'pages/deciduous'
    get 'pages/evergreen'
    get 'pages/herbacious'
    get 'pages/pictures'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plant.rb
################################################################################
# Model:  Plant
#
# Purpose:
#
# Plant attributes:
#   grower_id          - FK
#   title_la           - title_la:          string
#   title              - title:             string,  not NULL
#   hybrid_parentage   - hybrid_parentage:  string
#   kind               - kind:              enum { 0 | 1 | 2}
#   zone_min           - zone_min:          integer
#   zone_max           - zone_max:          integer
#   quantity           - quantity:          integer
#   planted_in         - year of planting:  integer
#   position           - sorting index:     integer, not NULL
#   status             - status:            enum { active (0) | archived (1) }
#
#  01.06.2017 ZT
################################################################################
class Plant < ApplicationRecord
  belongs_to  :grower
  has_many    :pictures
  before_save :set_position

  enum kind:   %w(deciduous evergreen herbacious)
  enum status: %w(active archived)

  validates :grower,   presence: true
  validates :title_la, presence: true
  validates :title,    presence: true
  validates :zone_min, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 11}
  validates :zone_max, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 11}
  validates :quantity, numericality: {greater_than_or_equal_to: 1}

  private

    def set_position
      if self.id.blank?
        last_item = Plant.order(:position).last
        self.position = last_item.blank? ? 1 : last_item.position.to_i + 1
      end
    end
end

app/controllers/admin/plants_controller.rb
class Admin::PlantsController < Admin::BaseController
  before_action :set_plant, only: [:show, :edit, :update,:destroy]

  def index
    @plants = policy_scope(Plant)
  end

  def show
    authorize @plant
  end

  def new
    @plant = Plant.new
    authorize @plant
  end

  def edit
    authorize @plant
  end

  def create
    @plant = Plant.new(plant_params)
    authorize @plant
    if @plant.save
      flash[:success] = t('messages.created', model: @plant.class.model_name.human)
      redirect_to [:admin, @plant]
    else      
      render :new
    end
  end

  def update
    authorize @plant
    if @plant.update(plant_params)
      flash[:success] = t('messages.updated', model: @plant.class.model_name.human)
      redirect_to [:admin, @plant]
    else      
      render :edit
    end
  end

  def destroy
    authorize @plant
    @plant.destroy
    flash[:success] = t('messages.deleted', model: @plant.class.model_name.human)
    redirect_to admin_plants_path
  end

  private

    # Uses callbacks to share common setup or constraints between actions
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Only allows a trusted parameter 'white list' through
    def plant_params
      params.require(:plant).permit(:grower_id, :title_la, :title, :hybrid_parentage, :kind, :zone_min, :zone_max, :quantity, :planted_in, :position, :status)
    end
end

app/views/admin/plants/_form.html.haml
.row
  .col-md-6
    = simple_form_for([:admin, @plant], html: {multipart: true}) do |f|
      = f.error_notification message: t('messages.error_notification')

      .form-inputs
        = f.association :grower, include_blank: false
        = f.input       :title_la
        = f.input       :title
        = f.input       :hybrid_parentage
        = f.input       :kind, include_blank: false
        = f.input       :zone_min, collection: [1,2,3,4,5,6,7,8,9,10,11], include_blank: false
        = f.input       :zone_max, collection: [1,2,3,4,5,6,7,8,9,10,11], include_blank: false
        = f.input       :quantity
        = f.input       :planted_in, collection: years_range
        = f.input       :position, as: :hidden

        = f.input :status, default: 1
        /= render 'admin/shared/status_buttons', f: f

      .form_actions
        .row
          .col-md-3
            = f.submit t('actions.save'), class: 'btn btn-primary btn-block'
          .col-md-3
            = link_to t('actions.back'), admin_plants_path, class: 'btn btn-default btn-block'

app/views/admin/plants/edit.html.haml
%h1= "#{t('actions.editing', model: @plant.class.model_name.human)}"
= render 'form'

app/views/admin/plants/index.html.haml
%h1= t Plant.model_name.human(count: 2)
%table.table.table-hover
  %thead
    %tr
      %th= Plant.human_attribute_name(:grower)
      %th= Plant.human_attribute_name(:title_la)
      %th= Plant.human_attribute_name(:title)
      %th= Plant.human_attribute_name(:hybrid_parentage)
      %th= Plant.human_attribute_name(:kind)
      /%th= Plant.human_attribute_name(:zone_min)
      /%th= Plant.human_attribute_name(:zone_max)
      /%th= Plant.human_attribute_name(:quantity)
      /%th= Plant.human_attribute_name(:planted_in)
      /%th= Plant.human_attribute_name(:position)
      %th= t 'status.status'
      %th= t 'actions.actions'

  %tbody
    - @plants.each do |plant|
      %tr
        %td= image_tag plant.grower.logo.thumb.url if plant.grower.logo?
        %td= plant.title_la
        %td= plant.title
        %td= plant.hybrid_parentage
        %td= plant.kind
        /%td= plant.zone_min
        /%td= plant.zone_max
        /%td= plant.quantity
        /%td= plant.planted_in
        /%td= plant.position
        %td= status_mark plant.status
        %td= render 'admin/shared/index_buttons', resource: plant
%br
.row
  .col-md-2
    = link_to t('actions.create'), new_admin_plant_path, class: 'btn btn-primary btn-block'

app/views/admin/plants/new.html.haml
%h1= "#{t('actions.new', model: @plant.class.model_name.human)}"
= render 'form'

app/views/admin/plants/show.html.haml
%h1= t Plant.model_name.human
%table.table.table-striped
  %tbody
    - @plant.attributes.each do |key, value|
      - if key == 'id' || key.include?('digest') || key == 'created_at' || key == 'updated_at'
        //skip these attributes
      -else
        %tr
          - if key == 'status'
            %td= t 'status.status'
            %td= status_mark @plant.status
          - elsif key == 'grower_id'
            %td= 'Grower'
            %td= image_tag @plant.grower.logo.thumb.url if @plant.grower.logo?
          -else
            %td= t "activerecord.attributes.plant.#{key}"
            %td= value

- if @plant.pictures.present?
  %h3= 'Pictures'
  %table.table.table-hover.table-condensed
    %thead
      %tr
        %th= Picture.human_attribute_name(:title)
        %th= Picture.human_attribute_name(:photo)
        %th= Picture.human_attribute_name(:kind)
        %th= Picture.human_attribute_name(:status)
        %th= t 'actions.actions'
    - @plant.pictures.each do |picture|
      %tr
        %td= picture.title
        %td= image_tag picture.photo.thumb.url if picture.photo?
        %td= picture.kind
        %td= picture.status
        %td
          = link_to t('actions.show'), admin_picture_path(picture.id),      class: 'btn btn-primary btn-xs'
          = link_to t('actions.edit'), edit_admin_picture_path(picture.id), class: 'btn btn-warning btn-xs'
  
    

.form_actions
  .row
    .col-md-2
      = link_to t('actions.back'), admin_plants_path, class: 'btn btn-primary btn-block'