config/routes.rb
Rails.application.routes.draw do

  if MULTILINGUAL

    scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

      # Session resources
      get    'sessions/new'                                 # sessions_new_path
      post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
      delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

      namespace :admin do
        root 'panel#index'                                  # admin_root_path
        resources :users
        resources :growers
        resources :plants
        resources :pictures
        resources :overviews
        resources :articles
        # 1: Add new admin resources before this line
      end

      root   'pages#home'                                   # root_path
      
      get 'pages/deciduous'
      get 'pages/evergreen'
      get 'pages/herbacious'
      get 'pages/pictures'
    end

    # Root route is directed to default locale
    root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

    # All other routes without locales are directed to the same ones with locales
    get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  else

    # Session resources
    get    'sessions/new'                                 # sessions_new_path
    post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
    delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

    namespace :admin do
      root 'panel#index'                                  # admin_root_path
      resources :users
      resources :growers
      resources :plants
      resources :pictures
      resources :overviews
      resources :articles
      # 2: Add new admin resources before this line
    end

    root   'pages#home'                                   # root_path

    get 'pages/deciduous'
    get 'pages/evergreen'
    get 'pages/herbacious'
    get 'pages/pictures'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/overviews_controller.rb
class Admin::OverviewsController < Admin::BaseController
  before_action :set_overview, only: [:show, :edit, :update,:destroy]
  after_action  :remove_image_dir, only: :destroy

  def index
    @overviews = policy_scope(Overview)
  end

  def show
    authorize @overview
  end

  def new
    @overview = Overview.new
    authorize @overview
  end

  def edit
    authorize @overview
  end

  def create
    @overview = Overview.new(overview_params)
    authorize @overview
    if @overview.save
      flash[:success] = t('messages.created', model: @overview.class.model_name.human)
      redirect_to [:admin, @overview]
    else      
      render :new
    end
  end

  def update
    authorize @overview
    if @overview.update(overview_params)
      flash[:success] = t('messages.updated', model: @overview.class.model_name.human)
      redirect_to [:admin, @overview]
    else      
      render :edit
    end
  end

  def destroy
    authorize @overview
    @overview.destroy
    flash[:success] = t('messages.deleted', model: @overview.class.model_name.human)
    redirect_to admin_overviews_path
  end

  private

    # Removes upload image directory of a destroyed Overview
    def remove_image_dir
      dir =  "public/uploads/overview/image/#{@overview.id}"
      FileUtils.remove_dir dir if Dir.empty?(dir)
    end

    # Uses callbacks to share common setup or constraints between actions
    def set_overview
      @overview = Overview.find(params[:id])
    end

    # Only allows a trusted parameter 'white list' through
    def overview_params
      params.require(:overview).permit(:name, :title, :carousel, :content, :image, :taken_at, :position, :status, :remove_image)
    end
end

app/views/admin/overviews/_form.html.haml
.row
  .col-md-6
    = simple_form_for([:admin, @overview], html: {multipart: true}) do |f|
      = f.error_notification message: t('messages.error_notification')

      .form-inputs
        = f.input :name
        = f.input :title
        = f.input :carousel
        = f.input :content
        /= f.input :image
        = f.input :taken_at
        = f.input :position, as: :hidden

        .input-group-addon
          = f.input :image, as: :file
          - if f.object.image?
            .input-group
              = image_tag @overview.image.thumb.url
              .input-group-addon
                = f.input :remove_image, as: :boolean

        = f.input :status, default: 1
        /= render 'admin/shared/status_buttons', f: f

      .form_actions
        .row
          .col-md-3
            = f.submit t('actions.save'), class: 'btn btn-primary btn-block'
          .col-md-3
            = link_to t('actions.back'), admin_overviews_path, class: 'btn btn-default btn-block'

app/views/admin/overviews/edit.html.haml
%h1= "#{t('actions.editing', model: @overview.class.model_name.human)}"
= render 'form'

app/views/admin/overviews/index.html.haml
%h1= t Overview.model_name.human(count: 2)
%table.table.table-hover
  %thead
    %tr
      %th= Overview.human_attribute_name(:name)
      %th= Overview.human_attribute_name(:title)
      %th= Overview.human_attribute_name(:carousel)
      /%th= Overview.human_attribute_name(:content)
      %th= Overview.human_attribute_name(:image)
      %th= Overview.human_attribute_name(:taken_at)
      %th= Overview.human_attribute_name(:position)
      %th= t 'status.status'
      %th= t 'actions.actions'

  %tbody
    - @overviews.each do |overview|
      %tr
        %td= overview.name
        %td= overview.title
        %td= status_mark overview.carousel?
        /%td= overview.content
        %td= image_tag overview.image.thumb.url if overview.image?
        %td= overview.taken_at
        %td= overview.position
        %td= status_mark overview.status
        %td= render 'admin/shared/index_buttons', resource: overview
%br
.row
  .col-md-2
    = link_to t('actions.create'), new_admin_overview_path, class: 'btn btn-primary btn-block'

app/views/admin/overviews/new.html.haml
%h1= "#{t('actions.new', model: @overview.class.model_name.human)}"
= render 'form'

app/views/admin/overviews/show.html.haml
%h1= t Overview.model_name.human
%table.table.table-striped
  %tbody
    - @overview.attributes.each do |key, value|
      - if key == 'id' || key.include?('digest') || key == 'created_at' || key == 'updated_at'
        //skip these attributes
      -else
        %tr
          - if key == 'status'
            %td= t 'status.status'
            %td= status_mark @overview.status
          - elsif key == 'carousel'
            %td= t 'status.carousel'
            %td= status_mark @overview.carousel?
          - elsif key == 'image'
            %td= t 'image'
            %td= image_tag @overview.image.preview.url if @overview.image?
          -else
            %td= t "activerecord.attributes.overview.#{key}"
            %td= value

.form_actions
  .row
    .col-md-2
      = link_to t('actions.back'), admin_overviews_path, class: 'btn btn-primary btn-block'