config/routes.rb
Rails.application.routes.draw do

  if MULTILINGUAL

    scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

      # Session resources
      get    'sessions/new'                                 # sessions_new_path
      post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
      delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

      namespace :admin do
        root 'panel#index'                                  # admin_root_path
        resources :users
        resources :growers
        resources :plants
        resources :pictures
        resources :overviews
        resources :articles
        # 1: Add new admin resources before this line
      end

      root   'pages#home'                                   # root_path
      
      get 'pages/deciduous'
      get 'pages/evergreen'
      get 'pages/herbacious'
      get 'pages/pictures'
    end

    # Root route is directed to default locale
    root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

    # All other routes without locales are directed to the same ones with locales
    get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  else

    # Session resources
    get    'sessions/new'                                 # sessions_new_path
    post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
    delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

    namespace :admin do
      root 'panel#index'                                  # admin_root_path
      resources :users
      resources :growers
      resources :plants
      resources :pictures
      resources :overviews
      resources :articles
      # 2: Add new admin resources before this line
    end

    root   'pages#home'                                   # root_path

    get 'pages/deciduous'
    get 'pages/evergreen'
    get 'pages/herbacious'
    get 'pages/pictures'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/deciduous.html.haml
%h1= "Deciduous Plants"

- if @deciduous_plants.present?
  = render "shared/covers", plants: @deciduous_plants
- else
  %h3= "This page is under construction"

app/views/pages/evergreen.html.haml
%h1= "Evergreen Plants"

- if @evergreen_plants.present?
  = render "shared/covers", plants: @evergreen_plants
- else
  %h3= "This page is under construction"

app/views/pages/herbacious.html.haml
%h1= "Herbacious Plants"

- if @herbacious_plants.present?
  = render "shared/plants_with_cover", plants: @herbaciousplants
- else
  %h3= "This page is under construction"

app/views/pages/home.html.haml
%h1 Welcome!

= render("shared/carousel_images",   images:   @carousel_images) if @carousel_images.present?
= render("shared/carousel_contents", articles: @articles)        if @articles.present?
/= render "shared/content"
.container-fluid
  .row
    .col-md-4
      - if @deciduous_cover.image.present?
        .wrapper
          = link_to image_tag(@deciduous_cover.image.cover.url),  pages_deciduous_path
          .description
            .text-center.description_content= "Deciduous Plants"
      - else
        = link_to "Deciduous Plants", pages_deciduous_path
    .col-md-4
      - if @evergreen_cover.image.present?
        .wrapper
          = link_to image_tag(@evergreen_cover.image.cover.url),  pages_evergreen_path
          .description
            .text-center.description_content= "Evergreen Plants"
      - else
        = link_to "Evergreen Plants", pages_evergreen_path
    .col-md-4
      - if @herbacious_cover.image.present?
        .wrapper
          = link_to image_tag(@herbacious_cover.image.cover.url),  pages_herbacious_path
          .description
            .text-center.description_content= "Herbacious Plants"
      - else
        = link_to "Herbacious Plants", pages_herbacious_path

-# if current_page? root_path
  .data-turbolinks-permanent= audio_tag "/audios/glazunov.mp3", :autoplay => true, :type => "audio/mp3", :controls => true, :loop => true
/= audio_tag "/audios/glazunov.mp3", :autoplay => true

app/views/pages/pictures.html.haml
.container
  .container
  %h1.text-center= "#{@plant.title}"
  %h2.text-center= "(#{@plant.title_la})"
  /.row= "Grower: #{@plant.grower.title}"
  /.row= "Hybrid Parentage: #{@plant.hybrid_parentage}"
  %h3.text-center= "USDA Zone: #{@plant.zone_min} - #{@plant.zone_max}"
  /.row= "Number of plants: #{@plant.quantity}"
  /.row= "Planted in: #{@plant.planted_in}"
  
  %br
  - @pictures.each do |picture|
    = link_to image_tag(picture.photo.preview.url, height: '200'), picture.photo.view.url, data: {lightbox: "example-set", title: picture_date(picture.taken_at)}

:javascript
  // see: http://lokeshdhakar.com/projects/lightbox2/
  lightbox.option({
    'wrapAround':        true,
    'albumLabel':        "Image %1 of %2",
  })