config/routes.rb
Rails.application.routes.draw do

  if MULTILINGUAL

    scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

      # Session resources
      get    'sessions/new'                                 # sessions_new_path
      post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
      delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

      namespace :admin do
        root 'panel#index'                                  # admin_root_path
        resources :users
        resources :growers
        resources :plants
        resources :pictures
        resources :overviews
        resources :articles
        # 1: Add new admin resources before this line
      end

      root   'pages#home'                                   # root_path
      
      get 'pages/deciduous'
      get 'pages/evergreen'
      get 'pages/herbacious'
      get 'pages/pictures'
    end

    # Root route is directed to default locale
    root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

    # All other routes without locales are directed to the same ones with locales
    get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  else

    # Session resources
    get    'sessions/new'                                 # sessions_new_path
    post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
    delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

    namespace :admin do
      root 'panel#index'                                  # admin_root_path
      resources :users
      resources :growers
      resources :plants
      resources :pictures
      resources :overviews
      resources :articles
      # 2: Add new admin resources before this line
    end

    root   'pages#home'                                   # root_path

    get 'pages/deciduous'
    get 'pages/evergreen'
    get 'pages/herbacious'
    get 'pages/pictures'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_top_navigation.html.haml
/ source: http://www.w3schools.com/bootstrap/bootstrap_navbar.asp

%nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      / Brand and toggle get grouped for better mobile display
      %button.navbar-toggle{"data-target" => ".collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand
        = link_to app_name.upcase, root_path
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to admin_root_path do
            %span.glyphicon.glyphicon-home
            = t(:admin_home)
        %li
          - if @current_user.sysadmin?
            = link_to admin_users_path do
              %span.glyphicon.glyphicon-user
              = t(:admin_users)
          - else
            = link_to edit_admin_user_path(@current_user) do
              %span.glyphicon.glyphicon-user
              = t(:profile)

        %li.dropdown
          = link_to '#', data: {toggle: "dropdown"}, class: "dropdown-toggle" do
            %span.glyphicon.glyphicon-th-list
            = t :data
            %span.caret
          %ul.dropdown-menu
            %li= link_to t(:growers),   admin_growers_path
            %li= link_to t(:plants),    admin_plants_path
            %li= link_to t(:pictures),  admin_pictures_path
            %li= link_to t(:overviews), admin_overviews_path
      %ul.nav.navbar-nav.navbar-right
        - if MULTILINGUAL
          %li.dropdown
            = link_to '#', data: {toggle: "dropdown"}, class: "dropdown-toggle" do
              = t :language
              %span.caret
            = language_switch_bootstrap('admin')
        %li
          = link_to(logout_path, method: 'delete') do
            %span.glyphicon.glyphicon-log-out
            = t 'simple_form.submit.logout'

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade in" style="top: auto; padding-top: 30px;">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "ZT Admin Module"  %> </title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'apple-touch-icon' %>
    <%= render 'shared/shim' %>
  </head>

  <body>
    <%= render 'layouts/flash_messages', flash: flash %>

    <%= render 'layouts/admin_top_navigation' %>
    <%= yield %>
  </body>

  <%= render 'shared/footer' %>
</html>

app/views/layouts/admin_header.html.haml
%h3 Admin_header.html.haml

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZtAdminApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'apple-touch-icon' %>
    <%= render 'shared/shim' %>
  </head>

  <body>
    <%= render 'shared/top_navigation' %>
    <%= yield %>
    <!--% if current_page? root_path %>
      <div data-turbolinks-permanent>
        <audio controls autoplay>
          <source src="/audios/zt.m4a" type="audio/mpeg">
        </audio>
      </div>
   <#% end %-->
    <!--% if current_page? root_path %>
      <%#= audio_tag "/audios/zt.m4a", :autoplay => true, :type => "audio/mp3", :controls => true, :loop => true, :data-turbolinks-permanent => true %>
    <!--% end %-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </body>

  <%= render 'shared/footer' %>
</html>